### ISSUE TITLE
rebalance function

### ISSUE THREAD

**Issue by Onoam** [Onoam/WAVLTree#25]
I think rebalancing should be done somewhere along the lines of 
`private static void/int rebalance(WAVLNode x, WAVLNode y)` i.e. getting an edge.
It should check the cases according to rank differences, and call separate helper methods for the actual rebalancing. 
I'm on that

**Comment by Onoam** [comment]
We might also want to do two functions, one for delete rebalancing and one for insert rebalancing.

**Comment by eytan-c** [comment]
also add case checking functions for insert and delete
