### ISSUE TITLE
There are still several compilation errors in master

### ISSUE THREAD

**Issue by Onoam** [Onoam/WAVLTree#30]
Please figure out what the problem with IDEA is, if it's not marking things like type mismatch (e.g. line 218) or constructor problems (line 20). 
[Maybe this might help?](https://intellij-support.jetbrains.com/hc/en-us/community/posts/206209539-Syntax-errors-not-displaying-in-the-editor-panel)
@eytan-c

**Comment by eytan-c** [comment]
I fixed most of them. The only remaining ones are regarding min/max.
I assumed the min/max accepting a WAVLNode also returned a WAVLNode (and that way we can use them in other functions)
Could you change them accordingly?

**Comment by Onoam** [comment]
Yeah I will change it
