### ISSUE TITLE
Add OuterNode as root of tree

### ISSUE THREAD

**Issue by Onoam** [Onoam/WAVLTree#39]
If while working on this you come to the conclusion it's unnecessary, let's talk about it.

**Comment by Onoam** [comment]
@eytan-c new debugging discovery:
If while inserting nodes to the tree, we have to rotate the root, it means the root has changed.
I manually added this check to `rotateLeft` and `rotateRight` so that  `if (node == root) {root = newnode}`, and that seems to have solved that issue.
However I got this null pointer exception after trying to `delete` the root from the tree:
![image](https://user-images.githubusercontent.com/29016914/50208485-f4882500-0379-11e9-99f8-19093566f2cc.png)
I think it's related, because if you have to replace the root with its successor for deletion, you need to update the root field (not just its parent). Same goes for deleting a root that's also a unary node or leaf (i.e. a tree that's just one node).
I think at this point it's better to just change the specific methods (`delete`/`remove`/`updateSizeUp`?) rather than add an OUTERNODE root, but I'm not sure, we might have more hidden bugs.

**Comment by Onoam** [comment]
Also I think I'm gonna have to spend a lot of time debugging until the due date, so the sooner you can finish the last bit of code remaining, the better for me :)

**Comment by eytan-c** [comment]
I actually think the easiest thing would be to add methods for removing the root in delete.
I'm adding it.

**Comment by eytan-c** [comment]
> @eytan-c new debugging discovery:
> If while inserting nodes to the tree, we have to rotate the root, it means the root has changed.
> I manually added this check to `rotateLeft` and `rotateRight` so that `if (node == root) {root = newnode}`, and that seems to have solved that issue.
> However I got this null pointer exception after trying to `delete` the root from the tree:
> ![image](https://user-images.githubusercontent.com/29016914/50208485-f4882500-0379-11e9-99f8-19093566f2cc.png)
> I think it's related, because if you have to replace the root with its successor for deletion, you need to update the root field (not just its parent). Same goes for deleting a root that's also a unary node or leaf (i.e. a tree that's just one node).
> I think at this point it's better to just change the specific methods (`delete`/`remove`/`updateSizeUp`?) rather than add an OUTERNODE root, but I'm not sure, we might have more hidden bugs.

I fixed in pull request #48
