### ISSUE TITLE
On reinserting a deleted node, an extra node with the same key appears

### ISSUE THREAD

**Issue by Onoam** [Onoam/WAVLTree#52]
My assumption is it was never deleted properly?
Reproducing it should work like this:
`insert(2), insert(5), delete(2), insert(2)`
![image](https://user-images.githubusercontent.com/29016914/50335576-6b592580-0514-11e9-8421-40dc5e8eaeb8.png)

**Comment by Onoam** [comment]
This doesn't seem to happen when removing a leaf:
![image](https://user-images.githubusercontent.com/29016914/50336122-01418000-0516-11e9-8325-e4e1099342c0.png)
But it does happen when removing an inner node that isn't the root.
I think the problem lies with removeRoot and remove:
![image](https://user-images.githubusercontent.com/29016914/50336168-174f4080-0516-11e9-8870-8ce93ce34e91.png)

I think the cases are:

1. node is a leaf
2. node is a unary node (in that case, bypass node)
![image](https://user-images.githubusercontent.com/29016914/50336283-77de7d80-0516-11e9-9fb2-a094bb2261ae.png)
3. node is a binary node (2 children). In this case only, we need to use "successor-swapping".

This can be seen in the BST presentation, slide 26-27

**Comment by eytan-c** [comment]
There is also a problem of deleting an unary node. But I think the issue with deleting the root is removing the pointer from the new root's parent. I'll fix both

**Comment by eytan-c** [comment]
And the case of the unary node doesn't happen in a WAVL tree, because then the tree is unbalanced. Ranks in pink, edges types in blue

![image](https://user-images.githubusercontent.com/29371190/50357869-1fcc6900-0560-11e9-96f0-6533bffac66c.png)

**Comment by eytan-c** [comment]
Update - I didn't set the old root to null + I didn't set the parent of the new root to null. Fixed both pull request #53

**Comment by Onoam** [comment]
> And the case of the unary node doesn't happen in a WAVL tree, because then the tree is unbalanced. Ranks in pink, edges types in blue
> 
> ![image](https://user-images.githubusercontent.com/29371190/50357869-1fcc6900-0560-11e9-96f0-6533bffac66c.png)

Unary node removal happens in the following situation:
![image](https://user-images.githubusercontent.com/29016914/50375674-28797980-060a-11e9-9a8f-b8fd00e57ca3.png)
It is very common. Specifically if you take that tree without the 9 node at the bottom, it is a valid WAVL tree and removing the 8 node is still something we need to handle. @eytan-c

**Comment by eytan-c** [comment]
Got it - will fix an push by end of tonight

**Comment by Onoam** [comment]
Sorry forgot to add: it seems like the unary node removal is working anyway. It's just binary node that is giving trouble (as of now):
![image](https://user-images.githubusercontent.com/29016914/50375727-ff0d1d80-060a-11e9-8cff-8c1d0249b4f8.png)

**Comment by eytan-c** [comment]
Solved (well, partially)
I added removing the values of the deleted node's fields. In practice, set:
`node.setParent(null)` , `node.setRight(OUTER_NODE)`, and `node.setLeft(OUTER_NODE). This gave me the following tree (which I'm not sure is balanced..., the rank diffs in node (6) is 0-2

![image](https://user-images.githubusercontent.com/29371190/50383436-21ab3f00-06bc-11e9-9f6c-09dbeb0489bf.png)

Waiting for reply before continuing, but validating that this happens in all cases
