### ISSUE TITLE
A strange bug when inserting: a large part of the tree disappears

### ISSUE THREAD

**Issue by Onoam** [Onoam/WAVLTree#54]
![image](https://user-images.githubusercontent.com/29016914/50376557-ff131a80-0616-11e9-9b51-64859bfba0cd.png)
I can't explain it. I have to go do other work, but I'll look further into this later.
The order of insertion:
17,6,1,19,18,3,2,10,13,12,20,15,4,11

**Comment by eytan-c** [comment]
might this be because of memory? I read in the forums that people were running out of memory

**Comment by Onoam** [comment]
I don't think so because it's a tiny tree (if it had 10,000 entries then maybe)
I think it's a rebalance problem, I'll keep trying to figure it out.

**Comment by Onoam** [comment]
The problem is resolved, I forgot to change a pointer in 'rotateLeft' and 'rotateRight'. I will add a pull request pretty soon.
