### ISSUE TITLE
What's with unlucky number 13?

### ISSUE THREAD

**Issue by Onoam** [Onoam/WAVLTree#59]
![image](https://user-images.githubusercontent.com/29016914/50420768-88a63080-0841-11e9-8388-e0e8be970393.png)
![image](https://user-images.githubusercontent.com/29016914/50420786-96f44c80-0841-11e9-87aa-d4758bb22ddc.png)
After attempting to fix `successor`, it seemed most balance problems were gone. (No printing of unbalanced trees occurred).
I added a printing method to Fast Insert a bunch of nodes, and then Fast Delete to delete all the nodes in random order.
However, every time it would die to a `NullPointerException`, and every time it was after exactly one delete after attempting to delete node 13, (which you may notice does not exist in the tree! (?)).
I will continue investigating.

**Comment by eytan-c** [comment]
13 is the root!

**Comment by eytan-c** [comment]
13 is the root
![image](https://user-images.githubusercontent.com/29371190/50422525-e5124b80-0853-11e9-894e-0f8bf24d37ee.png)
